
pytooling_library(
    "envoy.base.utils",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.core",
        "//deps:pyyaml",
        "//deps:pytz",
        "//deps:trycast",
    ],
)
