
toolshed_library(
    "envoy.dependency.check",
    sources=[
        "abstract/__init__.py",
        "abstract/checker.py",
        "abstract/dependency.py",
        "abstract/issues.py",
        "abstract/release.py",
        "checker.py",
        "cmd.py",
        "exceptions.py",
        "typing.py",
    ],
)
