
toolshed_tests(
    "aio.api.nist",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aiohttp",
        "//py/deps:reqs#packaging",
    ],
)
