
pytooling_library(
    "envoy.docs.sphinx_runner",
    dependencies=[
        "//deps:aio.run.runner",
        "//deps:envoy.base.utils",
        "//deps:colorama",
        "//deps:docutils",
        "//deps:pygments",
        "//deps:sphinx",
        "//deps:sphinx-copybutton",
        "//deps:sphinx-rtd-theme",
        "//deps:sphinx-tabs",
        "//deps:sphinxcontrib-httpdomain",
        "//deps:sphinxcontrib-serializinghtml",
        "//deps:sphinxext-rediraffe"
    ],
)
