
toolshed_library(
    "envoy.distribution.verify",
    dependencies=[
        "//py/deps:reqs#aio-run-checker",
        "//py/deps:reqs#envoy-base-utils",
        "//py/envoy.distribution.verify/envoy/distribution/distrotest",
    ],
)
