
pytooling_library(
    "envoy.github.abstract",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.core",
        "//deps:envoy.abstract.command",
        "//deps:envoy.base.runner",
    ],
)
