
pytooling_library(
    "envoy.github.abstract",
    dependencies=[
        "//deps:reqs#abstracts",
        "//deps:reqs#aio.core",
        "//deps:reqs#aio.run.runner",
        "//deps:reqs#aiohttp",
        "//deps:reqs#gidgethub",
    ],
)
