
toolshed_library(
    "envoy.distribution.release",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio.core",
        "//py/deps:reqs#aio.run.runner",
        "//py/deps:reqs#envoy.base.utils",
        "//py/deps:reqs#envoy.github.abstract",
        "//py/deps:reqs#envoy.github.release",
    ],
    tags=["abstract-types"],
)
