
toolshed_tests(
    "envoy.distribution.release",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/envoy.github.release/envoy/github/abstract",
    ],
)
