
toolshed_tests(
    "envoy.distribution.release",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#envoy-github-abstract",
        "//py/deps:reqs#envoy-github-release",
    ],
)
