
toolshed_tests(
    "envoy.distribution.release",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aio-run-runner",
        "//py/envoy.github.release/envoy/github/abstract",
        "//py/deps:reqs#envoy-github-release",
    ],
)
