
toolshed_tests(
    "aio.api.github",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aiohttp",
        "//py/deps:reqs#gidgethub",
        "//py/deps:reqs#packaging",
        "//py/deps:reqs#pytest-asyncio",
    ],
)
