workspace(name = "envoy_toolshed")

load(":archives.bzl", "load_archives")
load_archives()

load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

load(":toolchains.bzl", "load_toolchains")
load_toolchains()

load(":packages.bzl", "load_packages")
load_packages()

load("@toolshed_pip3//:requirements.bzl", "install_deps")
install_deps()
