workspace(name = "envoy_toolshed")

load(":archives.bzl", "load_archives")
load_archives()

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
bazel_skylib_workspace()

load("//v8:wee8_prebuilt.bzl", "setup_wee8_prebuilt")
setup_wee8_prebuilt()

load("//compile:llvm_minimal.bzl", "llvm_toolchain_alias", "setup_llvm_minimal")
setup_llvm_minimal()
llvm_toolchain_alias(
    name = "llvm_toolchain_llvm",
    minimal_linux_x64 = "@llvm_minimal_linux_x64//:BUILD.bazel",
    minimal_linux_arm64 = "@llvm_minimal_linux_arm64//:BUILD.bazel",
    minimal_macos_arm64 = "@llvm_minimal_macos_arm64//:BUILD.bazel",
)

load(":deps.bzl", "resolve_dependencies")
resolve_dependencies()

load(":toolchains_llvm.bzl", "setup_llvm_toolchain")
setup_llvm_toolchain()

load(":toolchains.bzl", "load_toolchains")
load_toolchains()

load(":packages.bzl", "load_packages", "load_website_packages")
load_packages()

load("@toolshed_pip3//:requirements.bzl", "install_deps")
install_deps()

load_website_packages()

load("@website_pip3//:requirements.bzl", website_install_deps = "install_deps")
website_install_deps()
