manifests:
# worker
- name: envoy-build
  tag: worker-{version}
  registry: docker.io/envoyproxy
  architectures:
  - amd64
  - arm64
  artifact-pattern: oci-debian-{arch}/envoy-build-worker-{version}-{arch}.tar
# worker (gcr)
- name: envoy-build
  tag: worker-{version}
  registry: gcr.io/envoy-ci
  architectures:
  - amd64
  - arm64
  artifact-pattern: oci-debian-{arch}/envoy-build-worker-{version}-{arch}.tar
# ci
- name: envoy-build
  tag: ci-{version}
  registry: docker.io/envoyproxy
  architectures:
  - amd64
  - arm64
  artifact-pattern: oci-debian-{arch}/envoy-build-ci-{version}-{arch}.tar
# gcc
- name: envoy-build
  tag: gcc-{version}
  registry: docker.io/envoyproxy
  architectures:
  - amd64
  - arm64
  artifact-pattern: oci-debian-{arch}/envoy-build-gcc-{version}-{arch}.tar
# gcc (gcr)
- name: envoy-build
  tag: gcc-{version}
  registry: gcr.io/envoy-ci
  architectures:
  - amd64
  - arm64
  artifact-pattern: oci-debian-{arch}/envoy-build-gcc-{version}-{arch}.tar
# devtools
- name: envoy-build
  tag: devtools-{version}
  registry: docker.io/envoyproxy
  architectures:
  - amd64
  - arm64
  artifact-pattern: oci-debian-{arch}/envoy-build-devtools-{version}-{arch}.tar
# docker
- name: envoy-build
  tag: docker-{version}
  registry: docker.io/envoyproxy
  architectures:
  - amd64
  - arm64
  artifact-pattern: oci-debian-{arch}/envoy-build-docker-{version}-{arch}.tar
# test
- name: envoy-build
  tag: test-{version}
  registry: docker.io/envoyproxy
  architectures:
  - amd64
  - arm64
  artifact-pattern: oci-debian-{arch}/envoy-build-test-{version}-{arch}.tar
# mobile (amd64 only)
- name: envoy-build
  tag: mobile-{version}
  registry: docker.io/envoyproxy
  architectures:
  - amd64
  artifact-pattern: oci-debian-{arch}/envoy-build-mobile-{version}-{arch}.tar
