inputs:
  caches:
    type: string
    required: true
  hits:
    type: string
    required: true

runs:
  using: "composite"
  steps:
  - uses: envoyproxy/toolshed/actions/foreach@1ac5ac77787d653454e60604edb4dc46ddd8110e
    id: json_actions
    with:
      items: ${{ inputs.caches }}
      context: ${{ inputs.hits }}
      steps: |
        - uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
          id: $KEY
          if: "%{{ fromJSON(inputs.context)['$KEY'] != true }}"
          with:
            key: $KEY
            path: "%{{ fromJSON(inputs.context).items['$KEY'] }}"
        - shell: bash
          if: "%{{ always() }}"
          run: |
            rm -rf "%{{ fromJSON(inputs.context).items['$KEY'] }}"
