inputs:
  key:
    type: string
    required: true

  key-copy:
    type: string
    default:
    description: |
      Path to copy key to. Must exist and be a directory.

outputs:
  key-path:
    value: ${{ steps.key.outputs.path }}
  key-copy-path:
    value: ${{ steps.key.outputs.copy-path }}


runs:
  using: "composite"
  steps:
  - uses: envoyproxy/toolshed/actions/github/script/run@80c3e8fccbda9aa39bd359c650e9822a741865bc
    id: key
    if: ${{ inputs.key }}
    with:
      run: |
        GCP_KEY_PATH=$(mktemp -t gcp_account.XXXXXX.json)
        echo "${{ inputs.key }}" | base64 --decode > "${GCP_KEY_PATH}"
        echo "path=${GCP_KEY_PATH}" >> $GITHUB_OUTPUT
        echo "GCP_KEY_PATH=${GCP_KEY_PATH}" >> $GITHUB_ENV
        if [[ -n "${{ inputs.key-copy }}" ]]; then
            if [[ ! -e "${{ inputs.key-copy }}" || ! -d "${{ inputs.key-copy }}" ]]; then
                echo "If set key-copy must exist and be a directory" >&2
                exit 1
            fi
            cp -a "$GCP_KEY_PATH" "${{ inputs.key-copy }}"
            GCP_KEY_FILENAME=$(basename $GCP_KEY_PATH)
            GCP_KEY_COPY_PATH="${{ inputs.key-copy }}/${GCP_KEY_FILENAME}"
            echo "GCP_KEY_COPY_PATH=${GCP_KEY_COPY_PATH}" >> $GITHUB_ENV
            echo "copy-path=${GCP_KEY_COPY_PATH}" >> $GITHUB_OUTPUT
        fi
        gcloud auth activate-service-account --key-file="${GCP_KEY_PATH}"
      post: |
        if [[ -e "${GCP_KEY_PATH}" ]]; then
            echo "Remove key ${GCP_KEY_PATH}"
            rm -rf "${GCP_KEY_PATH}"
        fi
        if [[ -n "${GCP_KEY_COPY_PATH}" && -e "${GCP_KEY_COPY_PATH}" ]]; then
            echo "Remove key ${GCP_KEY_COPY_PATH}"
            rm -rf "${GCP_KEY_COPY_PATH}"
        fi
  - run: |
      gcloud --version
    if: ${{ inputs.key }}
    shell: bash
