[mypy]
explicit_package_bases = True
namespace_packages = True
exclude = r'/setup\.py$|/conftest\.py$'
show_traceback = True
plugins =
    mypy_abstracts

# TODO: Remove this workaround for https://github.com/python/mypy/issues/21426
[mypy-aiodocker.*]
follow_imports = skip
