
toolshed_library(
    "envoy.github.abstract",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aio-run-runner",
        "//py/deps:reqs#aiohttp",
        "//py/deps:reqs#gidgethub",
    ],
)
