
pytooling_library(
    "envoy.distribution.repo",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.core",
        "//deps:envoy.base.runner",
        "//deps:envoy.base.utils",
    ],
)
