
pytooling_library(
    "envoy.distribution.repo",
    dependencies=[
        "//:abstracts",
        "//:aio.subprocess",
        "//:envoy.base.runner",
        "//:envoy.base.utils",
    ],
    tags=["abstract-types"],
)
