
python_tests(
    dependencies=[
        "//py/envoy.distribution.verify/envoy/distribution/distrotest",
        "//py/deps:reqs#aio-run-checker",
        "//py/deps:reqs#envoy-docker-utils",
        "//py/deps:reqs#pytest-abstracts",
        "//py/deps:reqs#pytest-asyncio",
        "//py/deps:reqs#pytest-iters",
        "//py/deps:reqs#pytest-patches",
    ],
    skip_mypy=True,
)
