
toolshed_tests(
    "envoy.code.check",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aio-run-checker",
        "//py/envoy.base.utils/envoy/base/utils",
        "//py/deps:reqs#flake8",
        "//py/deps:reqs#packaging",
        "//py/deps:reqs#pep8-naming",
        "//py/deps:reqs#yapf",
    ],
)
