
toolshed_tests(
    "envoy.code.check",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aio-run-checker",
        "//py/deps:reqs#envoy-base-utils",
        "//py/deps:reqs#flake8",
        "//py/deps:reqs#yapf",
    ],
)
