
resources(
    name="package_data",
    sources=["py.typed"])

python_sources(
    dependencies=[
        ":package_data",
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aio-run-runner",
        "//py/deps:reqs#aiohttp",
        "//py/deps:reqs#gidgethub",
    ],
)
