
toolshed_library(
    "aio.api.nist",
    sources=[
        "abstract/__init__.py",
        "abstract/cpe.py",
        "abstract/cve.py",
        "abstract/parser.py",
        "abstract/downloader.py",
        "abstract/matcher.py",
        "__init__.py",
        "exceptions.py",
        "interface.py",
        "nist.py",
        "typing.py",
    ],
)
