
pytooling_library(
    "envoy.code_format.python_check",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.core",
        "//aio.run.checker/aio/run/checker/__init__.py",
        # "//deps:envoy.base.checker",
        "//deps:envoy.base.utils",
    ],
    tags=["abstract-types"],
)
