
pytooling_library(
    "envoy.code_format.python_check",
    dependencies=[
        "//deps:abstracts",
        # "//deps:aio.core",
        "//aio.core/aio/core/__init__.py",
        "//deps:aio.run.checker",
    ],
    tags=["abstract-types"],
)
