
python_tests(
    dependencies=[
        "//py/envoy.gpg.sign/envoy/gpg/identity:envoy.gpg.identity",
        "//py/deps:reqs#pytest-abstracts",
        "//py/deps:reqs#pytest-asyncio",
        "//py/deps:reqs#pytest-iters",
        "//py/deps:reqs#pytest-patches",
    ],
    skip_mypy=True,
)
