"""Mock generator for testing the provider architecture."""

load("//website:providers.bzl", "WebsiteGeneratorInfo")

def _mock_generator_impl(ctx):
    """Implementation for mock generator."""
    # The mock generator script will be a simple shell script
    script = ctx.actions.declare_file(ctx.label.name + "_script.sh")
    
    ctx.actions.write(
        output = script,
        content = """#!/bin/bash
set -e

CONTENT_PATH="$1"
echo "Mock generator invoked with content path: $CONTENT_PATH"
echo "Accepted asset types: {accepts}"
echo "Output path: {output_path}"

# Create output directory
mkdir -p {output_path}

# Create a simple index.html
cat > {output_path}/index.html <<'EOF'
<!DOCTYPE html>
<html>
<head><title>Mock Generated Site</title></head>
<body>
<h1>Mock Generated Site</h1>
<p>This site was generated by the mock generator.</p>
<p>Content path: $CONTENT_PATH</p>
<p>Asset types: {accepts}</p>
</body>
</html>
EOF

echo "Mock generator completed successfully"
""".format(
            accepts = ", ".join(ctx.attr.accepts),
            output_path = ctx.attr.output_path,
        ),
        is_executable = True,
    )
    
    # Create WebsiteGeneratorInfo provider
    generator_info = WebsiteGeneratorInfo(
        executable = script,
        accepts = ctx.attr.accepts,
        output_path = ctx.attr.output_path,
        dev_server = None,
    )
    
    return [
        generator_info,
        DefaultInfo(
            executable = script,
            runfiles = ctx.runfiles(files = [script]),
        ),
    ]

mock_generator = rule(
    implementation = _mock_generator_impl,
    attrs = {
        "accepts": attr.string_list(
            mandatory = True,
            doc = "List of asset types this generator accepts",
        ),
        "output_path": attr.string(
            default = "output",
            doc = "Where the generator puts output",
        ),
    },
    executable = True,
    doc = "Mock generator for testing the website builder framework",
)
