module(
    name = "envoy_toolshed_jq",
    version = "0.4.16-dev",
    bazel_compatibility = [">=7.2.1"],
)

bazel_dep(name = "aspect_bazel_lib", version = "2.22.0")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "rules_shell", version = "0.8.0")

bazel_lib_toolchains = use_extension("@aspect_bazel_lib//lib:extensions.bzl", "toolchains")
bazel_lib_toolchains.jq(version = "1.7")
bazel_lib_toolchains.yq()
use_repo(bazel_lib_toolchains, "jq", "jq_toolchains", "yq", "yq_toolchains")
