toolshed_library(
    "envoy.docs.literalinclude",
    sources=[
        "__init__.py",
        "checker.py",
        "cmd.py",
        "fixer.py",
    ],
)

file(
    name="py_typed",
    source="py.typed",
)
