
pytooling_library(
    "envoy.distribution.verify",
    dependencies=[
        "//deps:packaging",
        "//deps:envoy.base.checker",
        "//deps:envoy.base.utils",
        "//deps:envoy.distribution.distrotest",
    ],
)
