
pytooling_library(
    "envoy.distribution.verify",
    dependencies=[
        "//:envoy.base.checker",
        "//:envoy.base.utils",
        "//:envoy.distribution.distrotest",
    ],
    tags=["abstract-types"],
)
