
pytooling_library(
    "envoy.distribution.release",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.functional",
        "//deps:envoy.abstract.command",
        "//deps:envoy.base.runner",
        "//deps:envoy.base.utils",
        "//deps:envoy.github.abstract",
        "//deps:envoy.github.release",
    ],
    tags=["abstract-types"],
)
