
pytooling_library(
    "envoy.distribution.release",
    dependencies=[
        "//:abstracts",
        "//:envoy.abstract.command",
        "//:envoy.base.runner",
        "//:envoy.base.utils",
        "//:envoy.github.abstract",
        "//:envoy.github.release",
    ],
    tags=["abstract-types"],
)
