#!/usr/bin/env bash

set -e

INPUT_YAML="$1"
OUTPUT_BZL="$2"

# Convert YAML to BZL using Python
python3 - "$INPUT_YAML" "$OUTPUT_BZL" << 'PYTHON_EOF'
import sys
import yaml
import json

input_file = sys.argv[1]
output_file = sys.argv[2]

# Read YAML
with open(input_file, 'r') as f:
    data = yaml.safe_load(f)

# Get sysroots list
sysroots = data.get('sysroots', [])

# Generate .bzl file
with open(output_file, 'w') as f:
    f.write('"""Auto-generated sysroot configuration from config.yaml."""\n\n')
    f.write('# DO NOT EDIT: This file is automatically generated from config.yaml\n')
    f.write('# Run: bazel build //sysroot:config_bzl to regenerate\n\n')
    f.write('SYSROOT_CONFIG = ')
    # Use json.dumps for proper Python/Starlark compatible format
    f.write(json.dumps(sysroots, indent=4))
    f.write('\n')

print(f"Generated {output_file} from {input_file}")
PYTHON_EOF
