
pytooling_library(
    "aio.api.bazel",
    dependencies=[
        "//deps:abstracts",
    ],
    sources=[
        "abstract/__init__.py",
        "abstract/base.py",
        "abstract/env.py",
        "abstract/query.py",
        "abstract/run.py",
        "__init__.py",
        "bazel.py",
        "exceptions.py",
    ],
)
