
toolshed_tests(
    "envoy.dependency.check",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-api-github",
        "//py/deps:reqs#aio-api-nist",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aio-run-checker",
        "//py/deps:reqs#envoy-base-utils",
        "//py/deps:reqs#aiohttp",
        "//py/deps:reqs#packaging",
    ],
)
