/* event-config_android.h
 *
 * This file was generated by running libevent's cmake configure against
 * Android NDK r26d at API level 23 (Android 6.0, the minimum SDK
 * targeted by Envoy Mobile), then adapted for Bazel in the same style
 * as event2-config_linux.h / event2-config_apple.h.
 *
 * NDK version : r26d  (android-ndk-r26d)
 * API level   : 23    (--target=x86_64-linux-android23 / arm64-android23)
 * Generated with:
 *   NDK=/path/to/android-ndk-r26d
 *   cmake /path/to/libevent-release-2.2.2-alpha \
 *     -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake \
 *     -DANDROID_ABI=x86_64 \
 *     -DANDROID_PLATFORM=android-23 \
 *     -DEVENT__DISABLE_TESTS=ON \
 *     -DEVENT__DISABLE_SAMPLES=ON \
 *     -DEVENT__DISABLE_BENCHMARK=ON
 *   cat build/include/event2/event-config.h
 *
 * API-level-sensitive macros (cross-check against NDK availability docs):
 *   arc4random / arc4random_buf : API 21+ — defined
 *   getifaddrs / freeifaddrs    : API 24+ — NOT defined (we target API 23)
 *   getrandom                   : API 28+ — NOT defined
 *   accept4                     : API 21+ — defined
 *   epoll_create1               : API 21+ — defined
 *   pipe2                       : API  9+ — defined
 *   timerfd_create              : API 19+ — defined
 *   strlcpy                     : always in bionic — defined
 *
 * If Envoy Mobile ever raises its minimum API level above 23, this file
 * should be regenerated at the new minimum.  A header generated at API 23
 * is conservative (correct but possibly disabling features available at
 * higher levels) rather than wrong, but regenerating picks up newer
 * functions automatically.
 *
 * This header targets 64-bit Android ABIs (arm64-v8a, x86_64).  For
 * 32-bit ABIs some sizeof values would differ; regenerate if needed.
 *
 * See the maintainer notes in //modules/libevent/README.md.
 *
 * Do not rely on macros in this file existing in later versions.
 */
#ifndef EVENT2_CONFIG_ANDROID_H_INCLUDED_
#define EVENT2_CONFIG_ANDROID_H_INCLUDED_

/* Define if libevent should build without support for a debug mode */
/* #undef EVENT__DISABLE_DEBUG_MODE */

/* Define if libevent should not allow replacing the mm functions */
/* #undef EVENT__DISABLE_MM_REPLACEMENT */

/* Define if libevent should not be compiled with thread support */
/* #undef EVENT__DISABLE_THREAD_SUPPORT */

/* Define to 1 if you have the `accept4' function. */
/* Available since Android API 21. */
#define EVENT__HAVE_ACCEPT4 1

/* Define to 1 if you have the `arc4random' function. */
/* Available since Android API 21 (bionic always provides it). */
#define EVENT__HAVE_ARC4RANDOM 1

/* Define to 1 if you have the `arc4random_buf' function. */
/* Available since Android API 21 (bionic always provides it). */
#define EVENT__HAVE_ARC4RANDOM_BUF 1

/* Define to 1 if you have the `arc4random_stir' function. */
/* #undef EVENT__HAVE_ARC4RANDOM_STIR */

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define EVENT__HAVE_ARPA_INET_H 1

/* Define to 1 if you have the `clock_gettime' function. */
#define EVENT__HAVE_CLOCK_GETTIME 1

/* Define to 1 if you have the declaration of `CTL_KERN'. */
#define EVENT__HAVE_DECL_CTL_KERN 0

/* Define to 1 if you have the declaration of `KERN_ARND'. */
#define EVENT__HAVE_DECL_KERN_ARND 0

/* Define to 1 if you have `getrandom' function. */
/* Not available until Android API 28; we target API 23. */
/* #undef EVENT__HAVE_GETRANDOM */

/* Define if /dev/poll is available */
/* #undef EVENT__HAVE_DEVPOLL */

/* Define to 1 if you have the <netdb.h> header file. */
#define EVENT__HAVE_NETDB_H 1

/* Define to 1 if fd_mask type is defined */
#define EVENT__HAVE_FD_MASK 1

/* Define if your system supports the epoll system calls */
#define EVENT__HAVE_EPOLL 1

/* Define to 1 if you have the `epoll_create1' function. */
/* Available since Android API 21. */
#define EVENT__HAVE_EPOLL_CREATE1 1

/* Define to 1 if you have the `epoll_pwait2' function. */
/* #undef EVENT__HAVE_EPOLL_PWAIT2 */

/* Define if your system supports the wepoll module */
/* #undef EVENT__HAVE_WEPOLL */

/* Define to 1 if you have the `eventfd' function. */
/* Available since Android API 21. */
#define EVENT__HAVE_EVENTFD 1

/* Define if your system supports event ports */
/* #undef EVENT__HAVE_EVENT_PORTS */

/* Define to 1 if you have the `fcntl' function. */
#define EVENT__HAVE_FCNTL 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define EVENT__HAVE_FCNTL_H 1

/* Define to 1 if you have the `getaddrinfo' function. */
#define EVENT__HAVE_GETADDRINFO 1

/* Define to 1 if you have the `getegid' function. */
#define EVENT__HAVE_GETEGID 1

/* Define to 1 if you have the `geteuid' function. */
#define EVENT__HAVE_GETEUID 1

/* TODO: Check for different gethostname argument counts. */
/* Define this if you have any gethostbyname_r() */
#define EVENT__HAVE_GETHOSTBYNAME_R 1

/* Define this if gethostbyname_r takes 3 arguments */
/* #undef EVENT__HAVE_GETHOSTBYNAME_R_3_ARG */

/* Define this if gethostbyname_r takes 5 arguments */
/* #undef EVENT__HAVE_GETHOSTBYNAME_R_5_ARG */

/* Define this if gethostbyname_r takes 6 arguments */
#define EVENT__HAVE_GETHOSTBYNAME_R_6_ARG 1

/* Define to 1 if you have the `getifaddrs' function. */
/* Not available until Android API 24; we target API 23. */
/* Without this, libevent falls back to /proc/net/if_inet6. */
/* #undef EVENT__HAVE_GETIFADDRS */

/* Define to 1 if you have the `getnameinfo' function. */
#define EVENT__HAVE_GETNAMEINFO 1

/* Define to 1 if you have the `getprotobynumber' function. */
#define EVENT__HAVE_GETPROTOBYNUMBER 1

/* Define to 1 if you have the `getservbyname' function. */
#define EVENT__HAVE_GETSERVBYNAME 1

/* Define to 1 if you have the `gettimeofday' function. */
#define EVENT__HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the <ifaddrs.h> header file. */
/* The header exists in NDK r26 for all API levels but getifaddrs()
 * itself requires API 24.  Libevent gates actual use on
 * EVENT__HAVE_GETIFADDRS, so it is safe to leave this defined. */
#define EVENT__HAVE_IFADDRS_H 1

/* Define to 1 if you have the `inet_ntop' function. */
#define EVENT__HAVE_INET_NTOP 1

/* Define to 1 if you have the `inet_pton' function. */
#define EVENT__HAVE_INET_PTON 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define EVENT__HAVE_INTTYPES_H 1

/* Define to 1 if you have the `issetugid' function. */
/* #undef EVENT__HAVE_ISSETUGID */

/* Define to 1 if you have the `kqueue' function. */
/* #undef EVENT__HAVE_KQUEUE */

/* Define if the system has zlib */
/* Not in the NDK sysroot; provided by the build system when needed. */
/* #undef EVENT__HAVE_LIBZ */

/* Define if the system has mbedtls */
/* #undef EVENT__HAVE_MBEDTLS */

/* Define to 1 if you have the `mach_absolute_time' function. */
/* #undef EVENT__HAVE_MACH_ABSOLUTE_TIME */

/* Define to 1 if you have the <mach/mach_time.h> header file. */
/* #undef EVENT__HAVE_MACH_MACH_TIME_H */

/* Define to 1 if you have the <mach/mach.h> header file. */
/* #undef EVENT__HAVE_MACH_MACH_H */

/* Define to 1 if you have the `mmap' function. */
#define EVENT__HAVE_MMAP 1

/* Define to 1 if you have the `mmap64' function. */
#define EVENT__HAVE_MMAP64 1

/* Define to 1 if you have the `nanosleep' function. */
#define EVENT__HAVE_NANOSLEEP 1

/* Define to 1 if you have the `usleep' function. */
#define EVENT__HAVE_USLEEP 1

/* Define to 1 if you have the <netinet/in6.h> header file. */
#define EVENT__HAVE_NETINET_IN6_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define EVENT__HAVE_NETINET_IN_H 1

/* Define to 1 if you have the <netinet/tcp.h> header file. */
#define EVENT__HAVE_NETINET_TCP_H 1

/* Define to 1 if you have the <sys/auxv.h> header file. */
#define EVENT__HAVE_SYS_AUXV_H 1

/* Define to 1 if you have the <sys/un.h> header file. */
#define EVENT__HAVE_SYS_UN_H 1

/* Define to 1 if you have the <afunix.h> header file. */
/* #undef EVENT__HAVE_AFUNIX_H */

/* Define if the system has openssl */
/* Not in the NDK sysroot; provided by the build system when needed. */
/* #undef EVENT__HAVE_OPENSSL */

/* Define to 1 if you have the `pipe' function. */
#define EVENT__HAVE_PIPE 1

/* Define to 1 if you have the `pipe2' function. */
/* Available since Android API 9. */
#define EVENT__HAVE_PIPE2 1

/* Define to 1 if you have the `poll' function. */
#define EVENT__HAVE_POLL 1

/* Define if we have pthreads on this system */
#define EVENT__HAVE_PTHREADS 1

/* Define to 1 if you have the `pthread_mutexattr_setprotocol' function. */
/* #undef EVENT__HAVE_PTHREAD_MUTEXATTR_SETPROTOCOL */

/* Define to 1 if you have the `putenv' function. */
#define EVENT__HAVE_PUTENV 1

/* Define to 1 if the system has the type `sa_family_t'. */
#define EVENT__HAVE_SA_FAMILY_T 1

/* Define to 1 if you have the `select' function. */
#define EVENT__HAVE_SELECT 1

/* Define to 1 if you have the `setenv' function. */
/* Available since Android API 21. */
#define EVENT__HAVE_SETENV 1

/* Define if F_SETFD is defined in <fcntl.h> */
#define EVENT__HAVE_SETFD 1

/* Define to 1 if you have the `setrlimit' function. */
#define EVENT__HAVE_SETRLIMIT 1

/* Define to 1 if you have the `sendfile' function. */
/* Available since Android API 21. */
#define EVENT__HAVE_SENDFILE 1

/* Define to 1 if you have the `pread' function. */
#define EVENT__HAVE_PREAD 1

/* Define to 1 if you have the `sigaction' function. */
#define EVENT__HAVE_SIGACTION 1

/* Define to 1 if you have the `socketpair' function. */
#define EVENT__HAVE_SOCKETPAIR 1

/* Define to 1 if you have the `strsignal' function. */
#define EVENT__HAVE_STRSIGNAL 1

/* Define to 1 if you have the <stdarg.h> header file. */
#define EVENT__HAVE_STDARG_H 1

/* Define to 1 if you have the <stddef.h> header file. */
#define EVENT__HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define EVENT__HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define EVENT__HAVE_STDLIB_H 1

/* Define to 1 if you have the <string.h> header file. */
#define EVENT__HAVE_STRING_H 1

/* Define to 1 if you have the `strlcpy' function. */
/* Always present in bionic (Android's libc). */
#define EVENT__HAVE_STRLCPY 1

/* Define to 1 if you have the `strndup' function. */
/* Available since Android API 21. */
#define EVENT__HAVE_STRNDUP 1

/* Define to 1 if you have the `strsep' function. */
/* Available via _GNU_SOURCE in bionic. */
#define EVENT__HAVE_STRSEP 1

/* Define to 1 if you have the `strtok_r' function. */
#define EVENT__HAVE_STRTOK_R 1

/* Define to 1 if you have the `strtoll' function. */
#define EVENT__HAVE_STRTOLL 1

/* Define to 1 if you have the `_gmtime64_s' function. */
/* #undef EVENT__HAVE__GMTIME64_S */

/* Define to 1 if you have the `_gmtime64' function. */
/* #undef EVENT__HAVE__GMTIME64 */

/* Define to 1 if you have the `BCryptGenRandom' function. */
/* #undef EVENT__HAVE_BCRYPTGENRANDOM */

/* Define to 1 if the system has the type `struct addrinfo'. */
#define EVENT__HAVE_STRUCT_ADDRINFO 1

/* Define to 1 if the system has the type `struct in6_addr'. */
#define EVENT__HAVE_STRUCT_IN6_ADDR 1

/* Define to 1 if the system has the type `struct sockaddr_in6'. */
#define EVENT__HAVE_STRUCT_SOCKADDR_IN6 1

/* Define to 1 if `sin6_len' is member of `struct sockaddr_in6'. */
/* #undef EVENT__HAVE_STRUCT_SOCKADDR_IN6_SIN6_LEN */

/* Define to 1 if `sin_len' is member of `struct sockaddr_in'. */
/* #undef EVENT__HAVE_STRUCT_SOCKADDR_IN_SIN_LEN */

/* Define to 1 if the system has the type `struct sockaddr_un'. */
#define EVENT__HAVE_STRUCT_SOCKADDR_UN 1

/* Define to 1 if the system has the type `struct sockaddr_storage'. */
#define EVENT__HAVE_STRUCT_SOCKADDR_STORAGE 1

/* Define to 1 if `ss_family' is a member of `struct sockaddr_storage'. */
#define EVENT__HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY 1

/* Define to 1 if `__ss_family' is a member of `struct sockaddr_storage'. */
/* #undef EVENT__HAVE_STRUCT_SOCKADDR_STORAGE___SS_FAMILY */

/* Define to 1 if the system has the type `struct linger'. */
#define EVENT__HAVE_STRUCT_LINGER 1

/* Define to 1 if you have the `sysctl' function. */
/* #undef EVENT__HAVE_SYSCTL */

/* Define to 1 if you have the <sys/eventfd.h> header file. */
/* Available since Android API 21. */
#define EVENT__HAVE_SYS_EVENTFD_H 1

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define EVENT__HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/mman.h> header file. */
#define EVENT__HAVE_SYS_MMAN_H 1

/* Define to 1 if you have the <sys/param.h> header file. */
#define EVENT__HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
#define EVENT__HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define EVENT__HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/sendfile.h> header file. */
/* Available since Android API 21. */
#define EVENT__HAVE_SYS_SENDFILE_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define EVENT__HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define EVENT__HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/random.h> header file. */
/* The header is present in NDK r26 for all API levels but getrandom()
 * itself requires API 28.  Libevent gates actual use on
 * EVENT__HAVE_GETRANDOM, so it is safe to leave this defined. */
#define EVENT__HAVE_SYS_RANDOM_H 1

/* Define to 1 if you have the <sys/sysctl.h> header file. */
/* #undef EVENT__HAVE_SYS_SYSCTL_H */

/* Define to 1 if you have the <sys/timerfd.h> header file. */
/* Available since Android API 19. */
#define EVENT__HAVE_SYS_TIMERFD_H 1

/* Define to 1 if you have the <sys/signalfd.h> header file. */
#define EVENT__HAVE_SYS_SIGNALFD_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define EVENT__HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define EVENT__HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/uio.h> header file. */
#define EVENT__HAVE_SYS_UIO_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
#define EVENT__HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <errno.h> header file. */
#define EVENT__HAVE_ERRNO_H 1

/* Define if timeradd is defined in <sys/time.h> */
#define EVENT__HAVE_TIMERADD 1

/* Define if timerclear is defined in <sys/time.h> */
#define EVENT__HAVE_TIMERCLEAR 1

/* Define to 1 if you have the `timerfd_create' function. */
/* Available since Android API 19. */
#define EVENT__HAVE_TIMERFD_CREATE 1

/* Define if timerisset is defined in <sys/time.h> */
#define EVENT__HAVE_TIMERISSET 1

/* Define to 1 if the system has the type `uint8_t'. */
#define EVENT__HAVE_UINT8_T 1

/* Define to 1 if the system has the type `uint16_t'. */
#define EVENT__HAVE_UINT16_T 1

/* Define to 1 if the system has the type `uint32_t'. */
#define EVENT__HAVE_UINT32_T 1

/* Define to 1 if the system has the type `uint64_t'. */
#define EVENT__HAVE_UINT64_T 1

/* Define to 1 if the system has the type `uintptr_t'. */
#define EVENT__HAVE_UINTPTR_T 1

/* Define to 1 if you have the `umask' function. */
/* Not available in bionic at API 23. */
/* #undef EVENT__HAVE_UMASK */

/* Define to 1 if you have the <unistd.h> header file. */
#define EVENT__HAVE_UNISTD_H 1

/* Define to 1 if you have the `unsetenv' function. */
#define EVENT__HAVE_UNSETENV 1

/* Define if kqueue works correctly with pipes */
/* #undef EVENT__HAVE_WORKING_KQUEUE */

#ifdef __USE_UNUSED_DEFINITIONS__
/* Define to necessary symbol if this constant uses a non-standard name on your system. */
#define EVENT__PTHREAD_CREATE_JOINABLE
#endif

/* The size of `pthread_t', as computed by sizeof. */
/* On Android, pthread_t is unsigned long (8 bytes on 64-bit ABIs). */
#define EVENT__SIZEOF_PTHREAD_T __SIZEOF_LONG__

/* The size of a `int', as computed by sizeof. */
#define EVENT__SIZEOF_INT __SIZEOF_INT__

/* The size of a `long', as computed by sizeof. */
#define EVENT__SIZEOF_LONG __SIZEOF_LONG__

/* The size of a `long long', as computed by sizeof. */
#define EVENT__SIZEOF_LONG_LONG __SIZEOF_LONG_LONG__

/* The size of `off_t', as computed by sizeof. */
#define EVENT__SIZEOF_OFF_T __SIZEOF_LONG__

/* The size of a `short', as computed by sizeof. */
#define EVENT__SIZEOF_SHORT __SIZEOF_SHORT__

/* The size of `size_t', as computed by sizeof. */
#define EVENT__SIZEOF_SIZE_T __SIZEOF_SIZE_T__

/* The size of `socklen_t', as computed by sizeof. */
/* socklen_t is always 4 bytes on Android. */
#define EVENT__SIZEOF_SOCKLEN_T 4

/* The size of 'void *', as computed by sizeof */
#define EVENT__SIZEOF_VOID_P __SIZEOF_POINTER__

/* The size of 'time_t', as computed by sizeof */
/* Bionic uses int64_t for time_t on all ABIs, including 32-bit. */
#define EVENT__SIZEOF_TIME_T 8

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* why not c++?
 *
 *  and are we really expected to use EVENT__inline everywhere,
 *  shouldn't we just do:
 *     ifdef EVENT__inline
 *     define inline EVENT__inline
 *
 * - Ellzey
 */

#define EVENT__inline inline
#endif

#define EVENT__HAVE___func__ 1
#define EVENT__HAVE___FUNCTION__ 1

/* Define to unsigned int if you dont have it */
#define EVENT__socklen_t socklen_t

/* Define to `int' if <sys/types.h> does not define. */
#define EVENT__ssize_t ssize_t

#endif /* EVENT2_CONFIG_ANDROID_H_INCLUDED_ */
