
pytooling_tests(
    "aio.api.github",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.core",
        "//deps:aiohttp",
        "//deps:gidgethub",
        "//deps:packaging",
        "//deps:pytest-asyncio",
    ],
)
