
toolshed_tests(
    "aio.api.github",
    dependencies=[
        "//deps:reqs#abstracts",
        "//deps:reqs#aio.core",
        "//deps:reqs#aiohttp",
        "//deps:reqs#gidgethub",
        "//deps:reqs#packaging",
        "//deps:reqs#pytest-asyncio",
    ],
)
