
toolshed_tests(
    "envoy.dependency.check",
    dependencies=[
        "//deps:reqs#abstracts",
        "//deps:reqs#aio.api.github",
        "//deps:reqs#aio.api.nist",
        "//deps:reqs#aio.core",
        "//deps:reqs#aio.run.checker",
        "//deps:reqs#envoy.base.utils",
        "//deps:reqs#aiohttp",
        "//deps:reqs#packaging",
    ],
)
