
pytooling_tests(
    "envoy.dependency.check",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.api.github",
        "//deps:aio.api.nist",
        "//deps:aio.core",
        "//deps:aio.run.checker",
        "//deps:envoy.base.utils",
        "//deps:aiohttp",
        "//deps:packaging",
    ],
)
