
pytooling_tests(
    "envoy.github.abstract",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.functional",
        "//deps:aio.tasks",
        "//deps:envoy.abstract.command",
        "//deps:pytest-asyncio",
    ],
)
