
pytooling_tests(
    "envoy.code.check",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.core",
        "//deps:aio.run.checker",
        "//deps:envoy.base.utils",
        "//deps:flake8",
        "//deps:yapf",
    ],
)
