
pytooling_tests(
    "envoy.code.check",
    dependencies=[
        "//deps:reqs#abstracts",
        "//deps:reqs#aio.core",
        "//deps:reqs#aio.run.checker",
        "//deps:reqs#envoy.base.utils",
        "//deps:reqs#flake8",
        "//deps:reqs#yapf",
    ],
)
