
pytooling_tests(
    "envoy.distribution.release",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.functional",
        "//deps:envoy.github.abstract",
        "//deps:envoy.github.release",
        "//deps:pytest-asyncio",
    ],
)
