
pytooling_tests(
    "envoy.distribution.release",
    dependencies=[
        "//deps:reqs#abstracts",
        "//deps:reqs#aio.core",
        "//deps:reqs#envoy.github.abstract",
        "//deps:reqs#envoy.github.release",
    ],
)
