
toolshed_tests(
    "envoy.docs.sphinx_runner",
    dependencies=[
        "//py/deps:reqs#aio-run-runner",
        "//py/deps:reqs#envoy-base-utils",
        "//py/deps:reqs#colorama",
        "//py/deps:reqs#sphinx",
        "//py/deps:reqs#sphinx-copybutton",
        "//py/deps:reqs#sphinxcontrib-httpdomain",
        "//py/deps:reqs#sphinxcontrib-serializinghtml",
        "//py/deps:reqs#sphinxext-rediraffe",
    ],
)
