inputs:
  debug:
    type: boolean
    default: false
  gpg-key:
    type: string
    default:
  gpg-password:
    type: string
    default:
  passphrase-path:
    type: string
  configured-passphrase-path:
    type: string

outputs:
  fingerprint:
    value: >-
      ${{ steps.gpg-import.outputs.fingerprint || steps.gpg.outputs.fingerprint }}
  passphrase:
    value: >-
      ${{ steps.gpg-import.outputs.passphrase || steps.gpg.outputs.passphrase }}


runs:
  using: "composite"
  steps:
  - name: Generate GPG key
    id: gpg
    if: >-
      inputs.gpg-key == ''
    uses: envoyproxy/toolshed/actions/gpg/generate@ab31cf868faba51af4bd9f04671c30d4084d70ee
    with:
      debug: ${{ inputs.debug }}
  - name: Import GPG key
    id: gpg-import
    if: >-
      inputs.gpg-key != ''
    uses: envoyproxy/toolshed/actions/gpg/import@ab31cf868faba51af4bd9f04671c30d4084d70ee
    with:
      key: ${{ inputs.gpg-key }}
      passphrase: ${{ inputs.gpg-password }}
      passphrase-path: ${{ inputs.passphrase-path }}
      configured-passphrase-path: ${{ inputs.configured-passphrase-path }}
