
toolshed_tests(
    "envoy.gpg.sign",
    dependencies=[
        "//py/deps:reqs#aio-run-runner",
        "//py/deps:reqs#envoy-base-utils",
        "//py/deps:reqs#verboselogs",
        "//py/envoy.gpg.sign/envoy/gpg/identity:envoy.gpg.identity",
    ],
)
