
toolshed_tests(
    "envoy.ci.report",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-api-github",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aio-run-runner",
    ],
)
