
pytooling_library(
    "aio.run.runner",
    dependencies=[
        "//deps:reqs#abstracts",
        "//deps:reqs#aio.core",
        "//deps:reqs#coloredlogs",
        "//deps:reqs#frozendict",
        "//deps:reqs#uvloop",
        "//deps:reqs#verboselogs",
    ],
)
