
pytooling_library(
    "aio.run.runner",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.core",
        "//deps:coloredlogs",
        "//deps:frozendict",
        "//deps:uvloop",
        "//deps:verboselogs",
    ],
)
