
pytooling_tests(
    "envoy.github.release",
    dependencies=[
        "//deps:aio.functional",
        "//deps:aio.tasks",
        "//deps:envoy.github.abstract",
        "//deps:pytest-asyncio",
    ],
)
