inputs:
  images:
    type: string
    required: true
  env_prefix:
    type: string
    default: OUTPUT

outputs:
  shas:
    value: ${{ steps.images.outputs.value }}


runs:
  using: composite
  steps:
  - uses: envoyproxy/toolshed/actions/jq@968a2ba272eeede13ddd934e72d19883a1b4fb8e
    id: yaml
    with:
      input: ${{ inputs.images }}
      input-format: yaml
  - uses: envoyproxy/toolshed/actions/foreach@968a2ba272eeede13ddd934e72d19883a1b4fb8e
    id: json_actions
    with:
      items: ${{ steps.yaml.outputs.value }}
      steps: |
        - uses: envoyproxy/toolshed/actions/docker/sha@43d5a16dd52f68e691841149617136d39d1cc1c2
          id: $KEY
          with:
            image: >-
              %{{ fromJSON(inputs.context).items['$KEY'] }}
            env_var: ${{ inputs.env_prefix }}_$KEY

  - uses: envoyproxy/toolshed/actions/jq@968a2ba272eeede13ddd934e72d19883a1b4fb8e
    id: images
    with:
      input: ${{ steps.json_actions.outputs.out }}
      filter: |
        .
        | fromjson
        | with_entries({key: .key, value: .value.outputs.sha})
