
pytooling_tests(
    "envoy.distribution.repo",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.functional",
        "//deps:envoy.base.runner",
        "//deps:envoy.base.utils",
        "//deps:pytest-asyncio",
    ],
)
