
toolshed_library(
    "envoy.github.release",
    tags=["abstract-types"],
    sources=[
        "__init__.py",
        "assets.py",
        "manager.py",
        "release.py",
        "stream/__init__.py",
        "stream/base.py",
        "stream/_reader.py",
        "stream/_writer.py",
    ],
)
