
pytooling_tests(
    "envoy.gpg.sign",
    dependencies=[
        "//deps:aio.run.runner",
        "//deps:envoy.base.utils",
        # TEMP: use local copy for testing until import is fixed
        # "//deps:envoy.gpg.identity",
        "//envoy.gpg.identity/envoy/gpg/identity/__init__.py",
    ],
)
