
toolshed_tests(
    "envoy.github.release",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aio-run-runner",
        "//py/deps:reqs#aiofiles",
        "//py/deps:reqs#aiohttp",
        "//py/deps:reqs#envoy-base-utils",
        "//py/deps:reqs#gidgethub",
        "//py/deps:reqs#packaging",
        "//py/deps:reqs#verboselogs",
        "//py/envoy.github.release/envoy/github/abstract",
    ],
)
