
pytooling_library(
    "aio.api.aspell",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.core",
    ],
    sources=[
        "abstract/__init__.py",
        "abstract/api.py",
        "__init__.py",
        "api.py",
        "exceptions.py",
        "utils.py",
    ],
)
