
pytooling_library(
    "envoy.docs.abstract",
    dependencies=[
        "//deps:abstracts",
        "//deps:envoy.base.utils",
        "//deps:envoy.base.runner",
        "//deps:frozendict",
        "//deps:protobuf",
        "//deps:jinja2",
    ],
)
