
pytooling_tests(
    "envoy.docs.sphinx_runner",
    dependencies=[
        "//deps:aio.run.runner",
        "//deps:envoy.base.utils",
        "//deps:colorama",
        "//deps:sphinx",
        "//deps:sphinx-copybutton",
        "//deps:sphinx-rtd-theme",
        "//deps:sphinx-tabs",
        "//deps:sphinxcontrib-httpdomain",
        "//deps:sphinxcontrib-serializinghtml",
        "//deps:sphinxext-rediraffe",
    ],
)
