
toolshed_tests(
    "envoy.docs.sphinx_runner",
    dependencies=[
        "//deps:reqs#aio.run.runner",
        "//deps:reqs#envoy.base.utils",
        "//deps:reqs#colorama",
        "//deps:reqs#sphinx",
        "//deps:reqs#sphinx-copybutton",
        "//deps:reqs#sphinxcontrib-httpdomain",
        "//deps:reqs#sphinxcontrib-serializinghtml",
        "//deps:reqs#sphinxext-rediraffe",
    ],
)
