
toolshed_tests(
    "envoy.distribution.repo",
    dependencies=[
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aio-run-runner",
        "//py/deps:reqs#envoy-base-utils",
        "//py/deps:reqs#pytest-asyncio",
    ],
)
