
pytooling_tests(
    "envoy.distribution.verify",
    dependencies=[
        "//:envoy.base.checker",
        "//:envoy.base.utils",
        "//:envoy.distribution.distrotest",
        "//:pytest-asyncio",
    ],
)
