
pytooling_tests(
    "envoy.distribution.verify",
    dependencies=[
        "//deps:envoy.base.checker",
        "//deps:envoy.base.utils",
        "//deps:envoy.distribution.distrotest",
        "//deps:pytest-asyncio",
    ],
)
