
toolshed_tests(
    "envoy.distribution.verify",
    dependencies=[
        "//deps:reqs#aio.run.checker",
        "//deps:reqs#envoy.base.utils",
        "//deps:reqs#envoy.distribution.distrotest",
    ],
)
