inputs:
  caches:
    type: string
    required: true

outputs:
  hits:
    value: ${{ steps.cached.outputs.value }}

runs:
  using: "composite"
  steps:
  - uses: envoyproxy/toolshed/actions/foreach@d51dcf45c47e0c8032567a5e7e6a7cb3f0095103
    id: json_actions
    with:
      items: ${{ inputs.caches }}
      steps: |
        - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
          id: $KEY
          with:
            key: $KEY
            path: "%{{ fromJSON(inputs.context).items['$KEY'] }}"

  - uses: envoyproxy/toolshed/actions/jq@d51dcf45c47e0c8032567a5e7e6a7cb3f0095103
    id: cached
    with:
      input: ${{ steps.json_actions.outputs.out }}
      print-result: true
      filter: |
        .
        | fromjson
        | with_entries({key: .key, value: (.value.outputs["cache-hit"] // "false" | fromjson)})
