
python_tests(
    dependencies=[
        "//py/envoy.github.release/envoy/github/abstract",
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio-core",
        "//py/deps:reqs#aio-run-runner",
        "//py/deps:reqs#pytest-abstracts",
        "//py/deps:reqs#pytest-asyncio",
        "//py/deps:reqs#pytest-iters",
        "//py/deps:reqs#pytest-patches",
    ],
    skip_mypy=True,
)
