load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

exports_files(["extension_utils.bzl"])

bzl_library(
    name = "extension_utils_bzl",
    srcs = ["extension_utils.bzl"],
    visibility = ["//visibility:public"],
)
