
toolshed_tests(
    "envoy.base.utils",
    dependencies=[
        ":data",
        "//py/deps:reqs#abstracts",
        "//py/deps:reqs#aio.api.github",
        "//py/deps:reqs#aio.core",
        "//py/deps:reqs#aio.run.runner",
        "//py/deps:reqs#pyyaml",
        "//py/deps:reqs#pytz",
        "//py/deps:reqs#trycast",
    ],
)

resources(
    name="data",
    sources=[
        "integration/**/*",
    ],
)
