
pytooling_library(
    "envoy.github.release",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.functional",
        "//deps:aio.stream",
        "//deps:aio.tasks",
        "//deps:envoy.github.abstract",
        "//deps:envoy.base.utils",
    ],
    tags=["abstract-types"],
)
