
pytooling_library(
    "envoy.github.release",
    dependencies=[
        "//deps:abstracts",
        "//deps:aio.core",
        "//deps:envoy.github.abstract",
        "//deps:envoy.base.utils",
    ],
    tags=["abstract-types"],
)
