name: Dependencies

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      action:
        description: Dependency action
        required: true
        type: choice
        options:
        - report
        - update-registry
        - update-module
      dependency:
        description: Dependency to update (update-module only), `name` or `name=version`
        type: string
        default:
      registry:
        description: Registry URL override (update-module only, passed as --registry=)
        type: string
        default:
      dry-run:
        description: Dry run (no PR created).
        type: boolean
        default: false
  schedule:
  - cron: '0 6 * * 1'

jobs:
  deps:
    secrets:
      app-id: >-
        ${{
          github.event_name == 'workflow_dispatch'
          && ! inputs.dry-run
          && secrets.ENVOY_CI_PUBLISH_APP_ID
          || ''
        }}
      app-key: >-
        ${{
          github.event_name == 'workflow_dispatch'
          && ! inputs.dry-run
          && secrets.ENVOY_CI_PUBLISH_APP_KEY
          || ''
        }}
    uses: ./.github/workflows/_deps.yml
    with:
      action: ${{ inputs.action || 'report' }}
      dependency: ${{ inputs.dependency || '' }}
      registry: ${{ inputs.registry || '' }}
      dry-run: ${{ github.event_name != 'workflow_dispatch' || inputs.dry-run }}
      branch: ${{ github.ref_name }}
      committer-name: publish-envoy[bot]
      committer-email: 140627008+publish-envoy[bot]@users.noreply.github.com
