name: Docker CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  request:
    runs-on: ubuntu-24.04
    outputs:
      run: ${{ steps.filter.outputs.run }}
    steps:
    - uses: envoyproxy/toolshed/actions/github/should-run@3d5bb981268f22161fa1c0c87bfc6828887c4e0e  # actions-v0.4.22
      id: filter
      with:
        config: |
          paths:
          - 'docker/build/**'
          - 'docker/echo/**'
          - '.github/workflows/docker.yml'
          - '.github/docker-manifests.yml'
          - 'docker/build/VERSION.txt'
          - 'docker-assets.yaml'
          - 'BINS_VERSION.txt'

  build:
    needs: request
    if: >-
      github.repository_owner == 'envoyproxy'
      && fromJSON(needs.request.outputs.run || 'false')
    strategy:
      fail-fast: false
      matrix:
        arch:
        - amd64
        - arm64
        target:
        - echo
        - build
    name: build ${{ matrix.target }} (${{ matrix.arch }})
    uses: ./.github/workflows/_docker.yml
    with:
      arch: ${{ matrix.arch }}
      target: ${{ matrix.target }}

  status:
    runs-on: ubuntu-24.04
    if: >-
      always()
      && github.event_name == 'pull_request'
    name: Docker
    needs:
    - request
    - build
    steps:
    - run: |
        if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled"
            exit 1
        fi
        echo "All required jobs passed or were skipped"
