name: Lint CI

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: "3.13"
    - run: pip install --require-hashes -r ci/requirements.txt
    - run: |
        envoy.code.check . -c glint shellcheck yamllint  -x ".*/dist/.*" -x "rust/glint/tests/fixtures/.*.txt"

  status:
    runs-on: ubuntu-24.04
    if: >-
      always()
      && github.event_name == 'pull_request'
    name: Lint
    needs:
    - lint
    steps:
    - run: |
        if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled"
            exit 1
        fi
        echo "All required jobs passed or were skipped"
