name: Publish release

permissions:
  contents: read

on:
  workflow_run:
    workflows:
    - Bazel CI
    - Docker CI
    - Github/actions CI
    - Python CI
    - Rust CI
    types:
    - completed


jobs:
  publish:
    if: >-
      github.event.workflow_run.event == 'push'
      && contains(fromJSON('["main", "workspace"]'), github.event.workflow_run.head_branch)
    permissions:
      actions: read
      contents: read
      id-token: write
    secrets:
      app-id: ${{ secrets.ENVOY_CI_PUBLISH_APP_ID }}
      app-key: ${{ secrets.ENVOY_CI_PUBLISH_APP_KEY }}
      gpg-key: ${{ secrets.ENVOY_GPG_MAINTAINER_KEY }}
      gpg-password: ${{ secrets.ENVOY_GPG_MAINTAINER_KEY_PASSWORD }}
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
      gcr-key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    uses: ./.github/workflows/_publish.yml
    with:
      branch: ${{ github.event.workflow_run.head_branch }}
      committer-email: "140627008+publish-envoy[bot]@users.noreply.github.com"
      committer-name: "publish-envoy[bot]"
      release-types: ${{ github.event.workflow_run.head_branch == 'workspace' && 'bazel' || 'actions bazel bins docker python' }}
      workflows: |
        Bazel CI
        ${{ github.event.workflow_run.head_branch == 'main' && 'Docker CI' || '' }}
        ${{ github.event.workflow_run.head_branch == 'main' && 'Github/actions CI' || '' }}
        ${{ github.event.workflow_run.head_branch == 'main' && 'Python CI' || '' }}
        ${{ github.event.workflow_run.head_branch == 'main' && 'Rust CI' || '' }}
