python_sources(
    skip_flake8 = True,
    skip_mypy = True,
    skip_docformatter = True,
    dependencies=[
        ":assets",
    ],
)

resources(
    name="assets",
    sources=[
        "./static/**/*.css",
        "./static/**/*.js"])
